### ISSUE TITLE
OpenRefine doesn't work on binder anymore

### ISSUE THREAD

**Issue by bitnik** [betatim/openrefineder#4]
Hi, I tried to launch `openrefineder` on [GESIS binder](https://notebooks.gesis.org/binder/), build and launch were successful but when I try to create a OpenRefine session, I get 500 error. This is the error in pod logs: `Error: OpenRefine requires Java version 6 or later. If you have multiple versions of Java installed, please set the environment variable JAVA_HOME to the correct version.`

This repo is already working on mybinder.org. So to be sure if the error is related to binder deployments or not, I forked this repo and launched the forked repo on mybinder.org but the result is the same.

The base image used in repo2docker was changed (https://github.com/jupyter/repo2docker/commit/ce88db7b833fff6f24225e5d9627cdd31bef2b5b) and I guess the problem is related to that. But I count't find a solution so far.

I just wanted to let you know that such a problem exists.

**Comment by betatim** [comment]
I guess something in the underlying Java installation has changed with the new base image. If someone who knows java has a moment to look at this, that would be great.

**Comment by betatim** [comment]
Works again now. Thanks for reporting this.
