### ISSUE TITLE
New `jupyter-server-proxy` setup

### ISSUE THREAD

**Issue by betatim** [betatim/openrefineder#7]
Switch to the new `jupyter-server-proxy` way of doing things:

https://jupyter-server-proxy.readthedocs.io/en/latest/server-process.html#specifying-config-from-python-packages

and 

https://github.com/jupyterhub/jupyter-rsession-proxy/blob/master/jupyter_rsession_proxy/__init__.py

**Comment by felixlohmeier** [comment]
It looks like Tony Hirst has already implemented this here: https://github.com/psychemedia/jupyterserverproxy-openrefine
